config/routes.rb
Rails.application.routes.draw do
  devise_for :users



  root to: 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :client do
    resources :treatments, only: [:new, :create, :index, :edit, :update, :destroy, :show]
  end

  resources :users, only: :show do
    resources :treatments, only: :index
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/town.rb
class Town < ApplicationRecord
  # belongs_to :user
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # enum role: [:client, :leader]

  # has_one :town

  has_many :treatments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    client_treatments_path
  end
end

app/controllers/client/treatments_controller.rb
class Client::TreatmentsController < ApplicationController
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]

   def index
     @treatments = current_user.treatments
   end

   def show
   end

   def new
     @treatment = Treatment.new
     # @town = current_user.town || Town.new
   end

   def create
     @treatment = Treatment.new(treatment_params)
     @treatment.user = current_user

     if @treatment.save
       redirect_to client_treatments_path(@treatment)
     else
       render :new
     end
   end

   def edit
   end

   def update
     @treatment.update(treatment_params)
     if @treatment.save
       redirect_to client_treatments_path(@treatment)
     else
       render :edit
     end
   end

   def destroy
     @treatment.destroy
     redirect_to client_treatments_path
   end

   private

   def set_treatment
     @treatment = Treatment.find(params[:id])
   end

   def treatment_params
     params.require(:treatment).permit(:user_id, :name, :start_date, :main_purpose, :other_purpose, :service_concerned, :service_function, :category_people_concerned, :personal_data, :sensitive_data, :recipient, :storage_time, :observation)
   end
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  layout 'public'
  def home
  end
end

app/controllers/treatments_controller.rb
# class TreatmentsController < ApplicationController
#   # before_action :set_project, only: :show
#
#   def index
#     @treatments = current_user.treatments.all
#   end
#
#   def show
#     @treatment = Treatment.find(params[:id])
#   end
#
#   def new
#     @treatment = Treatment.new
#     @town = current_user.town || Town.new
#     # render layout: false
#   end
#
#   def create
#     @town = current_user.town|| current_user.build_town(town_params)
#     @treatment = @town.treatments.new(treatment_params)
#
#     if @town.save && @town.save
#       redirect_to town_treatments_path, notice: "Votre traitement a bien été créé"
#     else
#       render :new
#     end
#   end
#
#   private
#
#   def town_params
#     params.require(:treatment).require(:town).permit(:city, :address, :mayor_name)
#   end
#
#   def treatment_params
#     params.require(:treatment).permit(:request_title, :request_description, :budget, :request_delivery_at)
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/client/treatments/_form.html.erb
<div class="form-instrument">
  <%= simple_form_for [:client, @treatment] do |t| %>
    <div class="form-inputs">
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :name %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :start_date %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :main_purpose %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :other_purpose %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :service_concerned %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :service_function %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :category_people_concerned %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :personal_data %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :sensitive_data %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :recipient %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :storage_time %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= t.input :observation %>
      </div>
      <div class="col-md-4 col-md-offset-4 center-btn">
        <div class="form-actions">
          <%= t.submit 'Done', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/client/treatments/index.html.erb
<div class="treatments">
  <div class="treatments-title">
    <h1>Mes traitements de données personnelles</h1>
    <%= link_to "Ajouter un traitement", new_client_treatment_path, class: "btn-add-treatment" %>
  </div>

  <div class="treatments-content">
    <div class="treatments-header">
      <div class="col5 col-sm-6">
        <p>Nom du traitement</p>
      </div>
      <div class="col5 col-sm-6">
        <p>Date de démarrage</p>
      </div>
      <div class="col5 col-sm-6">
        <p>Finalité principale</p>
      </div>
      <div class="col5 col-sm-6">
        <p>Service concerné</p>
      </div>
      <div class="col5 col-sm-6">
        <p> </p>
      </div>
    </div>

    <% @treatments.each do |treatment| %>
      <div class="treatment">
        <div class="col5 col-sm-6">
          <p><%= treatment.name %></p>
        </div>
        <div class="col5 col-sm-6">
          <p><%= treatment.start_date %></p>
        </div>
        <div class="col5 col-sm-6">
          <p><%= treatment.main_purpose %></p>
        </div>
        <div class="col5 col-sm-6">
          <p><%= treatment.service_concerned %></p>
        </div>
        <div class="col5 col-sm-6">
          <%= link_to "Voir", client_treatment_path(treatment), class: "btn-treatment" %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/client/treatments/new.html.erb
<div class="container">
  <h4 class="text-center page-title">Ajouter un traitement de données</h4>
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Orizon</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body class="application">
    <% unless devise_controller? %>
      <%= render "shared/sidebar" %>
    <% end %>
    <div class="content">
      <% if current_user.present? %>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <% end %>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Orizon</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body class="content">
    <div class="wrapper">
      <%= render "shared/navbar-home" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="large-header" class="large-header spirale">
  <canvas id="demo-canvas"></canvas>
    <h1 class="main-title">
      <span class="thin">ORIZON</span>
      <p class="subtitle">Smart data for smart decisions</p>
    </h1>
</div>


<!-- Banner présentation de la réglementation -->
<div class="container first-step-content city-orizon">
  <div class="col-md-12 content-center">
    <h1>LA RÉGLEMENTATION ÉVOLUE, VOS OBLIGATIONS AUSSI</h1>
    <h3>Le règlement général sur la protection des données prévoit des sanctions très sévères en cas de manquement à ses prescriptions, pouvant aller jusqu’à 4 millions d’euros ou 20% du chiffre d’affaire annuel.</h3>
    <h3>Orizon propose aux structures publiques (collectivités, établissements publics, associations…) et privées (TPE, ETI, PME…) une solution SaaS inédite de gestion et de traitement des données personnelles en parfaite conformité au cadre défini par le RGDP.</h3>
    <div class="btn-contact">
      <a href="" class="btn-blue">NOUS CONTACTER</a>
    </div>
  </div>
</div>

<!-- Banner notre solution -->
<div class="container second-step-content">
  <div class="col-md-12">
    <h1>NOTRE SOLUTION</h1>
    <div class="mini-feature col-md-4">
      <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/data-protection_rcxefl.png">
      <h3 class="mini-feature-heading">Vos données structurées</h3>
      <p class="mini-feature-description">Maîtrisez vos données grâce à une cartographie intégrale de vos traitements de données personnelles.
      </p>
    </div>
    <div class="mini-feature col-md-4">
      <img alt="Apps" src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/conformite_j9s2lg.png">
      <h3 class="mini-feature-heading">Votre conformité assurée</h3>
      <p class="mini-feature-description">Faites le choix de la conformité et reprenez le contrôle sur vos données personnelles.
      </p>
    </div>
    <div class="mini-feature col-md-4">
      <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/protegee_g1abdp.png">
      <h3 class="mini-feature-heading">Votre activité protégée</h3>
      <p class="mini-feature-description">Visualisez et gérez vos traitements de données personnelles en toute sécurité.
      </p>
    </div>
    </div>
  </div>
</div>

<!-- Banner présentation de la plateforme -->
<div class="container third-step-content">
  <div class="col-md-12">
    <h1>NOTRE PLATEFORME</h1>
    <div class="banner-plateforme-feature">
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-6">
            Aurevoir
          </div>
          <div class="col-md-6">
            Bonjour
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            Aurevoir
          </div>
          <div class="col-md-6">
            Bonjour
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="banner-plateforme-feature-photo hidden-xs">
          <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513339502/Macbook-orizon_k5cmsh.png">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Banner Contact -->
<div class="container fourth-step-content">
  <div class="col-md-12">
    <h1>NOUS CONTACTER</h1>

  </div>
</div>


<!-- Footer -->
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fa fa-heart"></i> at Paris
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar-home.html.erb
<div class="navbar-orizon-home">
  <!-- Right Navigation -->
  <div class="navbar-orizon-home-right hidden-xs hidden-sm">
    <a href="" class="navbar-orizon-home-item navbar-orizon-home-link">Nous contacter</a>
    <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-orizon-home-item navbar-orizon-home-link-connexion" %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-orizon-home-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-orizon-home-dropdown-menu">
        <li><a href="#">Nous contacter</a></li>
        <li><a href="#">Connexion</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-orizon">
  <!-- Logo -->


  <!-- Right Navigation -->
  <div class="navbar-orizon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%#= link_to "Traitements", "#", class: "navbar-orizon-item navbar-orizon-link" %>
      <%#= link_to "Responsable", "#", class: "navbar-orizon-item navbar-orizon-link" %>
      <%#= link_to "Déconnexion", "#", class: "navbar-orizon-item navbar-orizon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-orizon-item">
        <div class="dropdown">
          <%= image_tag "https://image.flaticon.com/icons/png/512/306/306473.png", class: "avatar dropdown-toggle", id: "navbar-orizon-menu", "data-toggle" => "dropdown" %>
          <%= link_to (current_user.first_name), "#", class: "navbar-orizon-item navbar-orizon-link dropdown-toggle", id: "navbar-orizon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-orizon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Réglages") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Déconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <!-- <div class="navbar-orizon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-orizon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar_color">
    <h2>ORIZON</h2>
  </div>

  <div class="container_menu side_menu pullRight">
    <%= link_to "Traitements", client_treatments_path %>
      <a href="#">Projets en cours</a>
      <a href="#">Statistiques</a>
      <a href="#">Documents</a>
      <a href="#">Déconnexion</a>
    </div>
  </div>
</div>